name: ci
on:
  push:
    branches: [main, release/*, release]
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.web.outputs.any_modified }}
      server: ${{ steps.server.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: changed files for web
        id: web
        uses: tj-actions/changed-files@v36
        with:
          files: |
            web
            # .github/workflows/ci.yml # TODO
            .github/workflows/ci_web.yml
            .github/workflows/build_web.yml
            .github/workflows/deploy_web_nightly.yml
            CHANGELOG.md

      - name: changed files for server
        id: server
        uses: tj-actions/changed-files@v36
        with:
          files: |
            server
            .github/workflows/ci.yml
            .github/workflows/ci_server.yml
            .github/workflows/build_server.yml
            .github/workflows/deploy_server_nightly.yml
            CHANGELOG.md

  ci-web:
    needs: prepare
    if: needs.prepare.outputs.web == 'true'
    uses: ./.github/workflows/ci_web.yml

  ci-server:
    needs: prepare
    if: needs.prepare.outputs.server == 'true'
    uses: ./.github/workflows/ci_server.yml

  ci:
    runs-on: ubuntu-latest
    needs:
      - ci-web
      - ci-server
    if: ${{ !failure() }}
    steps:
      - run: echo OK

  build-prepare:
    needs: prepare
    if: ${{ github.repository == 'reearth/reearth-visualizer' && github.event_name == 'push' && (github.ref_name == 'release' || !startsWith(github.event.head_commit.message, 'v')) }}
    uses: ./.github/workflows/build_prepare.yml

  build-web:
    needs: [ci-web, build-prepare]
    uses: ./.github/workflows/build_web.yml
    with:
      sha_short: ${{ needs.build-prepare.outputs.sha_short }}
      new_tag: ${{ needs.build-prepare.outputs.new_tag }}
      new_tag_short: ${{ needs.build-prepare.outputs.new_tag_short }}
      name: ${{ needs.build-prepare.outputs.name }}
      sha: ${{ github.sha }}
    secrets: inherit

  build-web-post:
    # needs build-web, but also this job should be triggered even if it was skipped
    needs: [build-prepare, build-web]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"

  build-server:
    needs: [ci-server, build-prepare, build-web-post] # build_server still requires web artifacts
    uses: ./.github/workflows/build_server.yml
    with:
      sha_short: ${{ needs.build-prepare.outputs.sha_short }}
      new_tag: ${{ needs.build-prepare.outputs.new_tag }}
      new_tag_short: ${{ needs.build-prepare.outputs.new_tag_short }}
      name: ${{ needs.build-prepare.outputs.name }}
      sha: ${{ github.sha }}
    secrets: inherit

  # TODO: build_release workflow is broken
  # build-release:
  #   needs: [ci-server, build-prepare, build-web-post]
  #   uses: ./.github/workflows/build_release.yml
  #   with:
  #     sha_short: ${{ needs.build-prepare.outputs.sha_short }}
  #     new_tag: ${{ needs.build-prepare.outputs.new_tag }}
  #     new_tag_short: ${{ needs.build-prepare.outputs.new_tag_short }}
  #     name: ${{ needs.build-prepare.outputs.name }}
  #     sha: ${{ github.sha }}
  #   secrets: inherit

  deploy-web:
    needs: build-web
    uses: ./.github/workflows/deploy_web_nightly.yml
    secrets: inherit

  deploy-server:
    needs: build-server
    uses: ./.github/workflows/deploy_server_nightly.yml
    secrets: inherit
